### ISSUE TITLE
begiak crash

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#402]
Begiak crashed today.  Phenny was still running, but disappeared from its channels.  This was the last part of the logs:

```
POLLING!!!!
12661 12661 {'vislcg3': 12661, 'marimorph': 4, 'hfst': 4671, 'gtrus': 164392, 'apertium': 84368}
t:  []
4 4 {'vislcg3': 12661, 'marimorph': 4, 'hfst': 4671, 'gtrus': 164392, 'apertium': 84368}
t:  []svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/apertium/svn'
svn: E120108: Error running context: The server unexpectedly closed the connection.
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
TypeError: 'MyHandler' object is not callable
ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 223, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/svnpoller.py", line 206, in pollsvn
    for (msg, revisions) in pollers[repo].check(global_revisions):
  File "/home/begiak/phenny/modules/svnpoller.py", line 63, in check
    self.latest_revision = self.get_last_revision()
  File "/home/begiak/phenny/modules/svnpoller.py", line 96, in get_last_revision
    tree = self.svn("info")
  File "/home/begiak/phenny/modules/svnpoller.py", line 91, in svn
    return ET.fromstring(data.decode())
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1345, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 3, column 0

ERROR: db type could not be determined
ERROR: db type could not be determined
```

**Comment by jonorthwash** [comment]
There's also some of these earlier in the logs:
```
----------------------------------------
Exception happened during processing of request from ('192.30.252.34', 61880)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.30.252.39', 40252)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.30.252.35', 42753)
----------------------------------------
```

**Comment by Androbin** [comment]
(svnpoller.py, awikstats.py, #389)
* POLLING!!!!
* Unable to connect to a repository at URL 'https://svn.code.sf.net/p/apertium/svn'
* xml.etree.ElementTree.ParseError: no element found: line 3, column 0

(git.py, 856bbc32ab11b5d1606be219cb96c1135b86a211)
* TypeError: 'MyHandler' object is not callable

(seen.py, shelve module, 78da9020f2afb5e2a9c3840b740a0be89026ab6a)
* ERROR: db type could not be determined

**Comment by Androbin** [comment]
Besides, how were they even able to mess with the connection?

**Comment by jonorthwash** [comment]
I don't understand your question.

**Comment by Androbin** [comment]
* I assume the crash was before the last two were fixed
* Either way, they are "sandboxed" (try-except)
* None of them touches the connection handling

**Comment by Androbin** [comment]
* Error running context: The server unexpectedly closed the connection.
* Phenny was still running, but disappeared from its channels.

Seems like it was just a disruption of the network connection.
We only retry connecting on startup, but don't reconnect after the connection was closed.
