### ISSUE TITLE
[mailing_list.py] decode_header TypeError

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#404]
I just pulled a bunch of updates.  Now when begiak is started up, it runs but doesn't join any channels. 
 This is what's at the end of the log:

```
INFO: Connecting to irc.freenode.net:6667...
INFO: connected!
INFO: Authorizing using SASL...
INFO: SASL Authentication successful.
INFO: #apertium
INFO: #hfst
INFO: ##ava
INFO: #matxin
INFO: #_u-dep
DEBUG: payload received; headers: Host: apertium.vm.bytemark.co.uk:1234
Accept: */*
User-Agent: GitHub-Hookshot/7a71d82
X-GitHub-Event: issues
X-GitHub-Delivery: 8c72c5f0-2973-11e8-915e-bb697dcf6ef3
content-type: application/x-www-form-urlencoded
Content-Length: 11490


192.30.252.37 - - [16/Mar/2018 23:41:35] "POST / HTTP/1.1" 200 -
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/home/begiak/phenny/modules/mailing_list.py", line 95, in check_mail
    message = format_email(e, name)
  File "/home/begiak/phenny/modules/mailing_list.py", line 67, in format_email
    subject = ''.join([t[0].decode(t[1] or 'utf-8') for t in decode_header(subject)])
  File "/home/begiak/phenny/modules/mailing_list.py", line 67, in <listcomp>
    subject = ''.join([t[0].decode(t[1] or 'utf-8') for t in decode_header(subject)])
AttributeError: 'str' object has no attribute 'decode'

DEBUG: payload received; headers: Host: apertium.vm.bytemark.co.uk:1234
Accept: */*
User-Agent: GitHub-Hookshot/7a71d82
X-GitHub-Event: issue_comment
X-GitHub-Delivery: d8b250b0-2974-11e8-81cb-42407cc27777
content-type: application/x-www-form-urlencoded
Content-Length: 13344


192.30.253.29 - - [16/Mar/2018 23:50:57] "POST / HTTP/1.1" 200 -
DEBUG: payload received; headers: Host: apertium.vm.bytemark.co.uk:1234
Accept: */*
User-Agent: GitHub-Hookshot/7a71d82
X-GitHub-Event: push
X-GitHub-Delivery: 4547aa36-2975-11e8-8bf4-6d1df3feb9b6
content-type: application/x-www-form-urlencoded
Content-Length: 11194
```

**Comment by Androbin** [comment]
(mailing_list.py, 2a4d59e87c33f0aa19e685fd701067e76f5aa919)
* AttributeError: 'str' object has no attribute 'decode'

This line was expecting to deal with bytes, not strings. Give me a moment...

**Comment by Androbin** [comment]
I think there is an issue with `proto.py # join` and the `keys` argument.

**Comment by Androbin** [comment]
@jonorthwash Could you try with SASL disabled?

**Comment by Androbin** [comment]
By the way, port 6697 offers SSL, 6667 does not.

**Comment by jonorthwash** [comment]
It's loading now, with SASL enabled.

**Comment by Androbin** [comment]
With the same commit and same configuration?

**Comment by jonorthwash** [comment]
Nah, I updated it.

**Comment by jonorthwash** [comment]
Though now we get other issues on startup:
```
INFO: Setting up phenny
ERROR: Error during setup of apertium_wikistats.py module:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 334, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 393, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 313, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='svn.code.sf.net', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 42, in module_control
    getattr(module, func)(phenny)
  File "/home/begiak/phenny/modules/apertium_wikistats.py", line 25, in setup
    r = requests.get(files[0], timeout=REQUEST_TIMEOUT)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='svn.code.sf.net', port=443): Read timed out. (read timeout=10)

INFO: Registered modules: admin, apertium_wiki, apertiumchill, apy, away, botfun, botsnack, calc, chillmeter, choose, clock, codepoints, commit, eightball, eleda, ethnologue, fcc, foodforus, fs_quotes, git, greeting, head, hs, imdb, info, iso639, lastfm, linx, logger, mailing_list, more, noexceptions, nsfw, pester, ping, queue, reload, remind, sasl, search, seen, sfissues, slogan, stache, startup, svnpoller, tell, urbandict, vtluugwiki, wadsworth, weather, weirdfun, wiki_count, wikipedia, wiktionary, wuvt
```

**Comment by jonorthwash** [comment]
We also get stuff like this:
```
192.30.252.37 - - [17/Mar/2018 17:33:12] "POST / HTTP/1.1" 200 -
DEBUG: payload received; headers: Host: apertium.vm.bytemark.co.uk:1234
Accept: */*
User-Agent: GitHub-Hookshot/7a71d82
X-GitHub-Event: issue_comment
X-GitHub-Delivery: d55a3050-2a09-11e8-964c-311fa2f0f2e1
content-type: application/x-www-form-urlencoded
Content-Length: 13740


192.30.252.45 - - [17/Mar/2018 17:37:41] "POST / HTTP/1.1" 200 -
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/home/begiak/phenny/modules/mailing_list.py", line 95, in check_mail
    message = format_email(e, name)
  File "/home/begiak/phenny/modules/mailing_list.py", line 67, in format_email
    subject = ''.join([str(t[0], t[1] or 'utf-8') for t in decode_header(subject)])
  File "/home/begiak/phenny/modules/mailing_list.py", line 67, in <listcomp>
    subject = ''.join([str(t[0], t[1] or 'utf-8') for t in decode_header(subject)])
TypeError: decoding str is not supported

```

**Comment by jonorthwash** [comment]
I'm using f64d6c3.

**Comment by Androbin** [comment]
The first few are -again- network timeouts. We should probably collapse the error messages.

**Comment by Androbin** [comment]
For `mailing_list.py`, could you print the value of `subject` that line uses?

**Comment by jonorthwash** [comment]
The value of `subject` that which line uses?  Also, how do I find the value of variables in a no longer running python script?

**Comment by Androbin** [comment]
Line 67 (see error message). I need just one sample to fix it, should this be run again.

**Comment by jonorthwash** [comment]
I'm afraid I don't understand.  What do you want me to do?

**Comment by Androbin** [comment]
I've read the docs again and apparently, there can be tuples `(str, None)` and stuff.
And apparently, there was a standard function doing exactly what we're trying to do.
