### ISSUE TITLE
github module crashes when payload is sent

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#490]
Information from the log:

140.82.115.251 - - [17/Nov/2019 21:39:58] "POST / HTTP/1.1" 200 -
DEBUG: responded '200' in 0.00s
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_nobloc
k
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 411, in handle_one_request
    self.wfile.flush() #actually send the response if not already done.
ValueError: I/O operation on closed file.
DEBUG: payload received; headers: Host: apertium.vm.bytemark.co.uk:1234
Accept: */*
User-Agent: GitHub-Hookshot/f1003bc
X-GitHub-Event: push
X-GitHub-Delivery: 7b09dd4a-098b-11ea-8db8-9dc5e5565961
content-type: application/x-www-form-urlencoded
Content-Length: 11571

192.30.252.88 - - [17/Nov/2019 22:42:06] "POST / HTTP/1.1" 200 -
DEBUG: responded '200' in 0.00s
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 411, in handle_one_request
    self.wfile.flush() #actually send the response if not already done.
ValueError: I/O operation on closed file.
DEBUG: payload received; headers: Host: apertium.vm.bytemark.co.uk:1234
Accept: */*
User-Agent: GitHub-Hookshot/f1003bc
X-GitHub-Event: push
X-GitHub-Delivery: a3832008-098e-11ea-86b8-2367babdb44b
content-type: application/x-www-form-urlencoded
Content-Length: 11559

**Comment by jonorthwash** [comment]
The crash happens right as any but the first payload is sent, but before `do_POST()` is entered.

**Comment by scoopgracie** [comment]
@jonorthwash i claimed this on gci, will you please assign me?

**Comment by scoopgracie** [comment]
Has this been fixed? It no longer seems to crash.
