### ISSUE TITLE
Fix ethnologue module

### ISSUE THREAD

**Issue by Androbin** [apertium/phenny#513]
```
======================================================================
ERROR: test_ethnologue (phenny.modules.test.test_ethnologue.TestEthnologue)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/apertium/phenny/modules/test/test_ethnologue.py", line 29, in test_ethnologue
    ethno.ethnologue(self.phenny, self.input)
  File "/home/travis/build/apertium/phenny/modules/ethnologue.py", line 85, in ethnologue
    if "macrolanguage" in h.find_class('field-name-a-language-of')[0].find('div/div/h2').text:
IndexError: list index out of range

======================================================================
ERROR: test_ethnologue_macrolanguage (phenny.modules.test.test_ethnologue.TestEthnologue)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/apertium/phenny/modules/test/test_ethnologue.py", line 36, in test_ethnologue_macrolanguage
    ethno.ethnologue(self.phenny, self.input)
  File "/home/travis/build/apertium/phenny/modules/ethnologue.py", line 85, in ethnologue
    if "macrolanguage" in h.find_class('field-name-a-language-of')[0].find('div/div/h2').text:
IndexError: list index out of range
```

**Comment by mr-martian** [comment]
When I run this test locally it works, so I wonder if this is maybe connected to Ethnologue having page view limits (I'm on college wifi so it's not limited)?

**Comment by mr-martian** [comment]
Since all the scraper is looking for is codes and names, we could change it to only requesting https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab

**Comment by scoopgracie** [comment]
Ethnologue module is now gone due to limitations.
