### ISSUE TITLE
Fix apy module tests

### ISSUE THREAD

**Issue by Androbin** [apertium/phenny#516]
```
======================================================================
ERROR: test_translate_admin (phenny.modules.test.test_apy.TestAPy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 114, in test_translate_admin
    self.check_exceptions(['eng-spa ' + self.texts['eng_long']],
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 56, in check_exceptions
    name.__call__(self.phenny, self.input)
  File "/home/travis/build/apertium/phenny/modules/apy.py", line 105, in apertium_translate
    translated = web.decode(translate(phenny, translated, input_lang, output_lang))
  File "/home/travis/build/apertium/phenny/modules/apy.py", line 71, in translate
    responseArray = json.loads(response.decode('utf-8'))
  File "/opt/python/3.8.0/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not MagicMock
======================================================================
FAIL: test_analyze_generate (phenny.modules.test.test_apy.TestAPy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 192, in test_analyze_generate
    self.check_exceptions([' '.join(words), 'eng'], apy.apertium_analyse)
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 56, in check_exceptions
    name.__call__(self.phenny, self.input)
AssertionError: GrumbleError not raised : No exception raised for invalid input to apertium_analyse!
======================================================================
FAIL: test_coverage (phenny.modules.test.test_apy.TestAPy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 227, in test_coverage
    self.check_exceptions(['eng', self.texts['eng'], 'eng-spa'], apy.apertium_calccoverage)
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 56, in check_exceptions
    name.__call__(self.phenny, self.input)
AssertionError: GrumbleError not raised : No exception raised for invalid input to apertium_calccoverage!
======================================================================
FAIL: test_perword (phenny.modules.test.test_apy.TestAPy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 253, in test_perword
    self.check_exceptions(['fra', 'fra (tagger)', '(tagger)', 'fra word',
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 56, in check_exceptions
    name.__call__(self.phenny, self.input)
AssertionError: GrumbleError not raised : No exception raised for invalid input to apertium_perword!
======================================================================
FAIL: test_translate_non_langs (phenny.modules.test.test_apy.TestAPy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 92, in test_translate_non_langs
    self.check_exceptions([self.texts['spa'], 'spa ' + self.texts['spa'], 'spa-eng'],
  File "/home/travis/build/apertium/phenny/modules/test/test_apy.py", line 56, in check_exceptions
    name.__call__(self.phenny, self.input)
AssertionError: GrumbleError not raised : No exception raised for invalid input to apertium_translate!
```

**Comment by Androbin** [comment]
See #504 @tomasff

**Comment by tomasff** [comment]
@Androbin Would it be acceptable to change the functions being tested in the apy module to return the error message instead of returning an empty value so that we can test it?

Or maybe instead of removing the GrumbleErrors in #504, would it be better if we had a `IncorrectUsageException` or adding an option on the GrumbleError exception so that we could now if it was a critical error or not and display the error message to the user or admins appropriately?
This would be using exceptions to control the program flow which doesn't seem great.

**Comment by jonorthwash** [comment]
I don't see a problem with this.  @Androbin?

**Comment by tomasff** [comment]
@jonorthwash would the exception modification be a better option than returning the error, even thought it implies using exceptions as control flow?

**Comment by Androbin** [comment]
> Would it be acceptable to change the functions being tested in the apy module to return the error message instead of returning an empty value so that we can test it?

We can either `raise` an error or return a special value where that is appropriate.

> Or maybe instead of removing the GrumbleErrors in #504, would it be better if we had a IncorrectUsageException ...

The `GrumbleError` type might be a bit to generic. Creating more suitable exception types would be a good task by itself.

> ... or adding an option on the GrumbleError exception so that we could know if it was a critical error or not and display the error message to the user or admins appropriately?

Remember that this is a ticket on tests. This shouldn't matter much for the tests themselves as we would want to test either type.
But if you find a reasonable way to classify errors (e.g. `IncorrectUsageException`) and a standard way of how to handle them, feel free to open a ticket for that.

**Comment by Androbin** [comment]
As long as this ticket is not replaced or superseded by another ticket, it would be sufficient to just make the build green again, so that we can test other change sets more easily.

**Comment by tomasff** [comment]
@Androbin I have submitted a pull request. As I explained in the description of the pr, it's not a very elegant solution, but should allow us to test the module for now if any changes are made.
