### ISSUE TITLE
Fix clock module tests

### ISSUE THREAD

**Issue by wei2912** [apertium/phenny#518]
```
======================================================================

ERROR: test_beats_normal (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17569

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17744

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_beats_zero (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17569

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_npl (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17569

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_time (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17742

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_time_multi (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17742

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17742

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_time_none (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17744

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17744

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_time_zone_convert_invalid (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17742

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_time_zone_convert_no_input (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17744

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_tock (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_yi_normal (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17742

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17744

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_yi_now (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17742

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

--------------------- >> end captured logging << ---------------------

======================================================================

ERROR: test_yi_soon (phenny.modules.test.test_clock.TestClock)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/apertium/phenny/web.py", line 62, in wrapper

    return fn(*args, **kw)

  File "/home/travis/build/apertium/phenny/modules/test/test_clock.py", line 24, in setUp

    clock.setup(self.phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 270, in setup

    scrape_wiki_zones(phenny)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 246, in scrape_wiki_zones

    phenny.time_zone_abbreviations = scrape_wiki_time_zone_abbreviations()

  File "/home/travis/build/apertium/phenny/web.py", line 78, in wrapper

    return fn(doc, *args, **kw)

  File "/home/travis/build/apertium/phenny/modules/clock.py", line 183, in scrape_wiki_time_zone_abbreviations

    name = cell.find('a').text

AttributeError: 'NoneType' object has no attribute 'text'

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17569

urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): en.wikipedia.org:443

urllib3.connectionpool: DEBUG: https://en.wikipedia.org:443 "GET /wiki/List_of_time_zone_abbreviations HTTP/1.1" 200 17747

--------------------- >> end captured logging << ---------------------
```

**Comment by wei2912** [comment]
See https://travis-ci.org/apertium/phenny/jobs/624319006; may be related to https://github.com/apertium/phenny/pull/503

**Comment by wei2912** [comment]
Seems to be fixed in the latest build, although I can't remember which PR fixed it.
