### ISSUE TITLE
whois module: greeting_db error

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#554]
We get the following error on startup:
```
ERROR: Error during setup of whois.py module:
Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 44, in module_control
    rephrase_errors(getattr(module, func), phenny)
  File "/home/begiak/phenny/tools.py", line 223, in rephrase_errors
    return fn(*args, **kw)
  File "/home/begiak/phenny/modules/whois.py", line 36, in setup
    connection = sqlite3.connect(self.greeting_db)
AttributeError: 'Phenny' object has no attribute 'greeting_db'
```

**Comment by scoopgracie** [comment]
Fixed by #551.

**Comment by jonorthwash** [comment]
I'm at revision 98b04a3 and I'm still getting the error.

**Comment by scoopgracie** [comment]
That's impossible... Line 36 of modules/whois.py at 98b04a3 does not refer
to phenny.greeting_db.

**Comment by scoopgracie** [comment]
Whois works as of right now.

**Comment by jonorthwash** [comment]
I think I must've been looking at old logs...
